package code;
// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class LoginideTest {
	static WebDriver driver;
	  
	private static Map<String, Object> vars;
  static JavascriptExecutor js;
  public static void main(String[] args){
	  
	  
	  driver = new FirefoxDriver();
	    js = (JavascriptExecutor) driver;
	    vars = new HashMap<String, Object>();
	 
	  
	driver.get("http://demowebshop.tricentis.com/");
    driver.manage().window().setSize(new Dimension(550, 691));
    driver.findElement(By.linkText("Log in")).click();
    driver.findElement(By.id("Email")).sendKeys("bala.murthy@gmail.com");
    driver.findElement(By.id("Password")).sendKeys("abcdef");
    driver.findElement(By.cssSelector(".login-button")).click();
    //assertThat(driver.findElement(By.linkText("Log out")).getText(), is("Log out"));
  }


  public void setUp() {
	    driver = new FirefoxDriver();
	    js = (JavascriptExecutor) driver;
	    vars = new HashMap<String, Object>();
	  }
	  public void tearDown() {
	    driver.quit();
	  }
	 
}
